# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.IntegerField(default=0)),
                ('content', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
