# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_celeryresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CeleryResults',
            new_name='XmlFeed',
        ),
    ]
